watcher_bee:
    resource: "@WatcherBeeBundle/Controller/"
    type:     annotation
    prefix:   /watcher

acme_test:
    resource: "@AcmeTestBundle/Controller/"
    type:     annotation
    prefix:   /

