watcher_bee:
    resource: "@WatcherBeeBundle/Controller/"
    type:     annotation
    prefix:   /watcher

acme_test:
    resource: "@AcmeTestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
