<?php

namespace Watcher\BeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpUserRepository extends EntityRepository
{
}
